### ISSUE TITLE
Bind parameters must not contain undefined. To pass SQL NULL specify JS null

### ISSUE THREAD

**Issue by SandFoxy** [Jasmisek/cloud-configs#5]
{
    "message": "Bind parameters must not contain undefined. To pass SQL NULL specify JS null"
}

Try to create config

**Comment by SandFoxy** [comment]
Bind parameters must not contain undefined. To pass SQL NULL specify JS null TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
    at /root/node_modules/mysql2/lib/connection.js:628:17
    at Array.forEach (<anonymous>)
    at Connection.execute (/root/node_modules/mysql2/lib/connection.js:620:22)
    at /root/node_modules/mysql2/promise.js:120:11
    at new Promise (<anonymous>)
    at PromiseConnection.execute (/root/node_modules/mysql2/promise.js:117:12)
    at Object.query (/root/src/services/db.service.js:6:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.create (/root/src/services/config.service.js:37:20)
    at async create (/root/src/controllers/config.controller.js:23:18)

**Comment by Jasmisek** [comment]
can you please tell me what you receive in the controller?

**Comment by Jasmisek** [comment]
I will be closing this issue because of inactivity.
